### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by pdxjohnny** [scumjr/dirtycow-vdso#12]
I've used some of your code, parts of payload.s and the shell catching part of 0xdeadbeef.c. I'd appreciate if you give this project a license as I want to open source my version and give credit to you.

**Comment by scumjr** [comment]
Here you go: 85b47efa9174a34874c65c281077057f697edf83 :-)

**Comment by pdxjohnny** [comment]
Hahaha had a feeling you'd choose that, thanks!

**Comment by pdxjohnny** [comment]
Sorry to bug you again but I have to go through my works legal to release my fork and they have no sense of humor. Could you use the BSD license or something?

I have it so that it works against any kernel (in a hackish way) and it uses proc self mem so it works with seccomp on. So Im hoping curiousity might persuade you to change it :-)

**Comment by scumjr** [comment]
I am not a lawyer but I think the WTFPL is GPL-compatible and approved by the FSF. Anyway, commit 0fe910a1e45a21a45ab08a02920312ba983a190b updates the projet under the MIT license.

**Comment by pdxjohnny** [comment]
Sick! Thanks again!
